# Generated by Django 5.2 on 2025-05-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_audio_file_album_created_at_album_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
