# Generated by Django 5.2 on 2025-05-09 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_track_uploaded_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='track',
            name='uploaded_by',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='Track', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
