# Generated by Django 5.2 on 2025-05-14 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_track_uploaded_at_track_uploaded_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_tracks', to=settings.AUTH_USER_MODEL),
        ),
    ]
