# Generated by Django 5.2 on 2025-05-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_track_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='liked_by',
        ),
    ]
