# Generated by Django 5.2 on 2025-05-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_trackreaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackreaction',
            name='is_like',
        ),
        migrations.AddField(
            model_name='trackreaction',
            name='reaction',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], default='LIKE', max_length=7),
            preserve_default=False,
        ),
    ]
