# Generated by Django 5.2 on 2025-05-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_listeninghistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListeningHistory',
        ),
    ]
