# Generated by Django 5.2 on 2025-05-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_listeninghistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListeningHistory',
        ),
    ]
